#!/bin/bash
# 
# queue
# 
# by Liam Strand, November 2021
# 
# Adds to the working queue
# 
# Usage: ./queue <comp class number>
# 

USERGROUPS=$(groups)

CLASS=$1


python queueDriver.py $USER $CLASS $USERGROUPS 